spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sssblog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # 静态资源
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/

  # redis配置
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456
      database: 0
      lettuce:
        pool:
          min-idle: 0
          max-idle: 8
          max-wait: -1ms
          max-active: 16

#  # RabbitMQ配置
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest

  # 邮件服务
  mail:
    host: smtp.qq.com
    port: 587
    username: ${MAIL_ACCOUNT}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# 服务器配置
server:
  port: 9000
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  tomcat:
    uri-encoding: UTF-8

# 日志配置
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.amqp: INFO
    com.example.config: DEBUG

# mybatis-plus配置
mybatis:
  mapper-locations: classpath:/mapper/*.xml
